### ISSUE TITLE
Update path

### ISSUE THREAD

**Issue by PaulFreund** [PocketSprite/8bkc-chooser#4]
I was wondering how to update the chooser withough opening and soldering. The chooser if fixed at the first partition and not an appfs app so we would have to do some kind of OTA. 

I saw your additions to the bootloader in the 8bkc-sdk to load esp images which is really nice, this can be handy sometime.

Do you already have a solution for ota chooser updates? Otherwise we could write a small updater app that can overwrite the chooser partition from an uploaded binary file if the battery state is okay. 

What do you think?

**Comment by Spritetm** [comment]
The bootloader and factory partition are locked shut (even with read-only blocks enabled in the bootloader) because it is your ticket out of anything that can happen when an app decides to mess up the appfs or the nvs. However, there's an upgrade path (because I'm not gonna trust myself to write a project as big as the chooser and be entirely bugless): if you dump a file called chooser.app into the appfs, the bootloader will (under normal circumstances) start that instead of the factory partition. That's the intended upgrade path. If you want to make use of that, just build the chooser using make, but rename build/chooser.bin and upload that using the WiFi interface instead of flashing it directly.

**Comment by PaulFreund** [comment]
Sorry I overlooked the chooser.app in the bootloader and you are right, with enough flash (provided) this is a lot better then overwriting the factory partition.

**Comment by PaulFreund** [comment]
PS: Maybe this update mechanism would be a good to document as a README.md. If you want I can offer to create one in a pull request including 
* Compiling
* Updating
* Recovery boot

**Comment by Spritetm** [comment]
Sure! Documentation on the chooser is a bit lacking because I focused on the SDK instead.
